#!/bin/bash

arch=$(uname -m)

if [[ $arch == x86_64* ]]; then
    architecture="x86-64"
elif [[ $arch == i*86 ]]; then
    architecture="i386"
elif  [[ $arch == arm64* ]] || [[ $arch = aarch64* ]]; then
	architecture="arm64"
else
	ynh_die "Unable to detect your achitecture, please open a bug describing \
        your hardware and the result of the command \"uname -m\"." 1
fi